# Generated by Django 5.0.4 on 2024-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaitapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuent',
            name='Password',
        ),
        migrations.AlterField(
            model_name='stuent',
            name='Contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stuent',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
