# Generated by Django 5.0.4 on 2024-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaitapp', '0003_user_delete_stuent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagename', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
